/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
#define ID_TEXT_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_11 (GUI_ID_USER + 0x0C)
// USER START (Optionally insert additional defines)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0D)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern WM_HWIN Menu_lock(void);
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
char unit[4][5]={"t","L","Kg","m3"};
float Caculation_para[4]={12312.23,34.423,543.3,346.145};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 16, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 16, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 32, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 0, 48, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 17, 0, 87, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 32, 16, 71, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 32, 32, 71, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 32, 48, 71, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 103, 0, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 103, 16, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 103, 32, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 103, 48, 24, 16, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 65, 1, 1, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char temp[20];
  static uint8_t times,mark1=0,htemp[10];
  uint8_t i;
  // USER END

  switch (pMsg->MsgId) {
      case WM_INIT_DIALOG:
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
            TEXT_SetText(hItem, "∑");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
            TEXT_SetText(hItem, "瞬时");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
            TEXT_SetText(hItem, "压力");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
            TEXT_SetText(hItem, "温度");
            TEXT_SetFont(hItem, &GUI_FontST16);
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            sprintf(temp,"%f",Caculation_para[0]);
            TEXT_SetText(hItem, temp);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            sprintf(temp,"%f",Caculation_para[1]);
            TEXT_SetText(hItem, temp);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            sprintf(temp,"%f",Caculation_para[2]);
            TEXT_SetText(hItem, temp);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
            TEXT_SetText(hItem, unit[2]);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            TEXT_SetText(hItem, unit[2]);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            TEXT_SetText(hItem, unit[2]);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetText(hItem, unit[2]);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            // USER START (Optionally insert additional code for further widget initialization)
            WM_CreateTimer(pMsg->hWin,0x01,200,0);
            WM_CreateTimer(pMsg->hWin,0x02,3000,0);
            for(i=0;i<12;i++)
                htemp[i]=WM_GetDialogItem(pMsg->hWin, GUI_ID_USER+i+1);
            // USER END
        break;
  // USER START (Optionally insert additional message handling)
    case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        Menu_lock();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
      case WM_TIMER:
        switch(WM_GetTimerId(pMsg->Data.v))
        {
            case 1:
                {
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
                    sprintf(temp,"%lf",measure.EF);
                    TEXT_SetText(hItem, temp);
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
                    sprintf(temp,"%lf",measure.F);
                    TEXT_SetText(hItem, temp);

                    //sprintf(temp,"%d",GUI_ALLOC_GetMaxSize());
                    if(mark1)
                        sprintf(temp,"%lf",measure.CY);
                    else
                        sprintf(temp,"%lf",measure.YL);
                    TEXT_SetText(htemp[6], temp);
                    if((measure.MODE>>3)&0x01)
                        sprintf(temp,"%lf",measure.PT);
                    else
                        sprintf(temp,"%lf",measure.T);
                    //sprintf(temp,"%d",GUI_ALLOC_GetNumFreeBytes());
                    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_7), temp);
                    WM_RestartTimer(pMsg->Data.v,50);
                }
                break;
            case 2:
                {
                    WM_RestartTimer(pMsg->Data.v,3000);
                    if((measure.MODE)>>1&0x01)
                    {
                         if(mark1==0)
                        {
                            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2), "压力");
                            mark1=1;
                        }
                        else
                        {
                            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2), "差压");
                            mark1=0;
                        }
                    }
                    else if(mark1==1)
                        TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2), "差压");
                }
                break;
        }

      break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Main_status(void);
WM_HWIN Main_status(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
