/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontm_font16;
extern WM_HWIN Main_status(void);
extern WM_HWIN Menulist_1(void);
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 5, 7, 36, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 46, 7, 36, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 87, 7, 36, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 5, 35, 36, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 46, 35, 36, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 87, 35, 36, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char temp[15];
  unsigned char i=0;
  static unsigned char POSITION_FOCUS=1,TIMES;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "通道");
    BUTTON_SetFont(hItem,&GUI_FontST16);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontST16);
    BUTTON_SetText(hItem, "补偿");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontST16);
    BUTTON_SetText(hItem, "输出");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_FontST16);
    BUTTON_SetText(hItem, "报警");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
   BUTTON_SetFont(hItem, &GUI_FontST16);
    BUTTON_SetText(hItem, "校准");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, &GUI_FontST16);
    BUTTON_SetText(hItem, "系统");
    // USER START (Optionally insert additional code for further widget initialization)
    TIMES=0;
    WM_CreateTimer(pMsg->hWin,0x01,30,0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        Tongdao();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        Buchang();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_UP:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
          TIMES=0;
            if(POSITION_FOCUS>=4)
                POSITION_FOCUS-=3;
            else
                POSITION_FOCUS+=3;
        }
        break;
    case GUI_KEY_DOWN:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
          TIMES=0;
            if(POSITION_FOCUS>=4)
                POSITION_FOCUS-=3;
            else
                POSITION_FOCUS+=3;
        }
        break;
    case GUI_KEY_LEFT:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
          TIMES=0;
            if((POSITION_FOCUS==1)||(POSITION_FOCUS==4))
                POSITION_FOCUS+=2;
            else
                POSITION_FOCUS-=1;
        }
        break;
    case GUI_KEY_RIGHT:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
          TIMES=0;
             if((POSITION_FOCUS==3)||(POSITION_FOCUS==6))
                POSITION_FOCUS-=2;
            else
                POSITION_FOCUS+=1;
        }
        break;
    }
    WM_SetFocus(WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + POSITION_FOCUS));
    //sprintf(temp,"%d",POSITION_FOCUS);
    //BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5), temp);
    break;
    case WM_TIMER:
      WM_RestartTimer(pMsg->Data.v,50);
        for(i=1;i<7;i++)
        {
            if(i==POSITION_FOCUS)
            {
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + i),BUTTON_CI_UNPRESSED,GUI_WHITE);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + i),BUTTON_CI_UNPRESSED,GUI_BLACK);
                GUI_Clear();
            }
            else
            {
               BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + i),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, GUI_ID_USER + i),BUTTON_CI_UNPRESSED,GUI_WHITE);
                GUI_Clear();
            }
        }
      if(TIMES++>100)
      {
        WM_DeleteWindow(pMsg->hWin);
        Main_status();
      } 
      break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Menu_list(void);
WM_HWIN Menu_list(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
