/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x03)
#define ID_TEXT_2 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 46, 25, 36, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 11, 128, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 0, 128, 10, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 45, 128, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern WM_HWIN Menu_list(void);
extern WM_HWIN Main_status(void);
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER START (Optionally insert additional variables)
  static unsigned char EDIT_0_S=1;
  static unsigned int TIMER_S=0;
  static unsigned char times=0;
  char temp[15];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0000");
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "解锁");
    TEXT_SetFont(hItem,&GUI_FontST16);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "2017/6/1");
    TEXT_SetFont(hItem, GUI_FONT_10_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "    ");
    // USER START (Optionally insert additional code for further widget initialization)
    //WM_SetCallback(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),_cbEdit0);
    EDIT_SetDecMode(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),0000,0,9999,0,0);
    EDIT_EnableBlink(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),500,1);
    EDIT_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),EDIT_CI_ENABLED,GUI_BLACK);
    EDIT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),EDIT_CI_ENABLED,GUI_WHITE);
    EDIT_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),EDIT_CI_DISABELD,GUI_BLACK);
    EDIT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),EDIT_CI_DISABELD,GUI_WHITE);
    WM_CreateTimer(pMsg->hWin,0x01,1000,0);
    EDIT_0_S=1;
    TIMER_S=0;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
        case GUI_KEY_ENTER:
                if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
                {
                    if(EDIT_0_S==1)
                    {
                        EDIT_EnableBlink(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),500,0);
                        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
                        if(EDIT_GetValue(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0))==0000)
                        {
                            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2),"SUCCESS");
                            EDIT_0_S=0;
                        }
                        else
                        {
                            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2),"ERROR");
                            EDIT_0_S=2;
                        }
                    }
                    else if(EDIT_0_S==2)
                     {
                         EDIT_0_S=1;
                         EDIT_EnableBlink(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),500,1);
                         WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
                     }
                }
        break;
    }
    break;
  case WM_TIMER:
      WM_RestartTimer(pMsg->Data.v,1000);
            if(EDIT_0_S==2)
            {
                if(TIMER_S++>2)
                {
                    WM_DeleteWindow(pMsg->hWin);
                    Main_status();
                }
            }
            else if(EDIT_0_S==1)
            {
                TIMER_S=0;
            }
            else if(EDIT_0_S==0)
            {
                if(TIMER_S++>1)
                {
                    WM_DeleteWindow(pMsg->hWin);
                    Menu_list();
                }
            }

    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Menu_lock(void);
WM_HWIN Menu_lock(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
