/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ST16.c                                                *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\xp\Desktop\font.txt                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ____X___,
  ____X___,
  ____X___,
  _XXXXXXX,
  ____X___,
  ____X___,
  ____X___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ______X_,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ____X___,
  __XXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  __XXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  ______X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _XXXXXXX,
  _____X__,
  _____X__,
  ___XXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_X_,
  ______X_,
  ______X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ___XX___,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  ____XX__,
  __XX_X__,
  _X___X__,
  _X__XX__,
  __XX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXX___,
  _X______,
  __XXXX__,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XXX____,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X__X_,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX_XX_,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  _XX_XXX_,
  ________,
  ________};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_00B0[ 32] = { /* code 00B0, DEGREE SIGN */
  ________,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_00B2[ 16] = { /* code 00B2, SUPERSCRIPT TWO */
  ________,
  ________,
  _XXX____,
  X__X____,
  ___X____,
  __X_____,
  _X__X___,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_00B3[ 16] = { /* code 00B3, SUPERSCRIPT THREE */
  ________,
  ________,
  _XXX____,
  ___X____,
  __X_____,
  ___X____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_2103[ 32] = { /* code 2103, DEGREE CELSIUS */
  _XX_____,________,
  X__X___X,XXXX_X__,
  X__X_XX_,____XX__,
  _XX_XX__,_____X__,
  ____X___,_____X__,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ____X___,________,
  ____XX__,_____X__,
  _____XX_,____X___,
  _______X,XXXX____,
  ________,________};

/* Start of unicode area <Mathematical Operators> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_2211[ 32] = { /* code 2211, N-ARY SUMMATION */
  ________,________,
  _XXXXXXX,XXXXXX__,
  __XX____,_____X__,
  ___XX___,_____X__,
  ____XX__,________,
  _____XX_,________,
  ______XX,________,
  _______X,X_______,
  _______X,________,
  ______X_,________,
  _____X__,________,
  ____X___,________,
  ___X____,_____X__,
  __X_____,_____X__,
  _XXXXXXX,XXXXXX__,
  ________,________};

/* Start of unicode area <Geometric Shapes> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_25B3[ 32] = { /* code 25B3, WHITE UP-POINTING TRIANGLE */
  ________,________,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  ___X____,___X____,
  __X_____,____X___,
  __X_____,____X___,
  _XXXXXXX,XXXXXX__,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_4E0A[ 32] = { /* code 4E0A */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_4E0B[ 32] = { /* code 4E0B */
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  ______X_,__X_____,
  ______X_,___X____,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_4F4D[ 32] = { /* code 4F4D */
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX____,________,
  __XX____,____X___,
  _X_X__X_,____X___,
  X__X__X_,____X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_4F8B[ 32] = { /* code 4F8B */
  ___X____,_____X__,
  ___X____,_____X__,
  ___X_XXX,XX___X__,
  __X___X_,___X_X__,
  __X___X_,___X_X__,
  _XX___XX,XX_X_X__,
  _XX___X_,_X_X_X__,
  X_X__X__,_X_X_X__,
  __X__XX_,_X_X_X__,
  __X__X_X,_X_X_X__,
  __X_X___,X__X_X__,
  __X_____,X__X_X__,
  __X____X,_____X__,
  __X___X_,_____X__,
  __X__X__,___X_X__,
  __X_X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_4FE1[ 32] = { /* code 4FE1 */
  ____X___,_X______,
  ____X___,__X_____,
  ____X_XX,XXXXXXX_,
  ___X____,________,
  ___X____,________,
  __XX___X,XXXXXX__,
  __XX____,________,
  _X_X____,________,
  X__X___X,XXXXXX__,
  ___X____,________,
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  ___X___X,XXXXXX__,
  ___X___X,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_503C[ 32] = { /* code 503C */
  ____X___,_X______,
  ____X___,_X______,
  ____XXXX,XXXXXX__,
  ___X____,_X______,
  ___X____,_X______,
  __XX__XX,XXXXX___,
  __XX__X_,____X___,
  _X_X__XX,XXXXX___,
  X__X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_507F[ 32] = { /* code 507F */
  ____X___,_X______,
  ____X_X_,_X__X___,
  ____X__X,_X_X____,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  __XX_X__,______X_,
  __XXX___,_____X__,
  _X_X___X,XXXX____,
  X__X____,________,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  ___X____,X_______,
  ___X___X,___X____,
  ___X__X_,____X___,
  ___X_XXX,XXXXXX__,
  ___X__X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5165[ 32] = { /* code 5165 */
  _____X__,________,
  ______X_,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,___X____,
  _X______,____X___,
  X_______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_51B5[ 32] = { /* code 51B5 */
  ________,________,
  _X___XXX,XXXXX___,
  __X__X__,____X___,
  __X__X__,____X___,
  _____X__,____X___,
  _____X__,____X___,
  ___X_XXX,XXXXX___,
  ___X___X,__X_____,
  __X____X,__X_____,
  XXX____X,__X_____,
  __X____X,__X_____,
  __X___X_,__X_____,
  __X___X_,__X___X_,
  __X__X__,__X___X_,
  __X_X___,___XXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_51C6[ 32] = { /* code 51C6 */
  _______X,_X______,
  _X_____X,__X_____,
  __X____X,__X_____,
  __X___XX,XXXXXXX_,
  ______X_,__X_____,
  ___X_XX_,__X_____,
  ___XX_XX,XXXXXX__,
  ___X__X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXXXXX__,
  XXX___X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXXXXXX_,
  __X___X_,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_51FA[ 32] = { /* code 51FA */
  _______X,________,
  _______X,________,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  _______X,____X___,
  _______X,________,
  _______X,________,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _XXXXXXX,XXXXXX__,
  ________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5207[ 32] = { /* code 5207 */
  ___X____,________,
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___XXXX_,_X___X__,
  XXXX____,_X___X__,
  ___X____,_X___X__,
  ___X____,_X___X__,
  ___X__X_,_X___X__,
  ___X_X__,_X___X__,
  ___XX___,X____X__,
  ___X____,X____X__,
  _______X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_529B[ 32] = { /* code 529B */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXXX___,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,____X___,
  ______X_,____X___,
  _____X__,____X___,
  _____X__,____X___,
  ____X___,____X___,
  ____X___,____X___,
  ___X____,X___X___,
  __X_____,_X_X____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_52A8[ 32] = { /* code 52A8 */
  ________,_X______,
  ________,_X______,
  _XXXXX__,_X______,
  ________,_X______,
  _______X,XXXXXX__,
  ________,_X___X__,
  XXXXXXX_,_X___X__,
  __X_____,_X___X__,
  __X_____,_X___X__,
  __X_____,X____X__,
  _X__X___,X____X__,
  _X___X__,X____X__,
  XXXXXX_X,_____X__,
  _X___X_X,_____X__,
  ______X_,__X_X___,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5355[ 32] = { /* code 5355 */
  ___X____,___X____,
  ____X___,__X_____,
  _____X__,_X______,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_538B[ 32] = { /* code 538B */
  ________,________,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X__X____,
  __X_____,X___X___,
  __X_____,X___X___,
  _X______,X_______,
  _X_XXXXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_53F7[ 32] = { /* code 53F7 */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  ____X___,________,
  ___X____,________,
  ___XXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_578B[ 32] = { /* code 578B */
  ________,_____X__,
  _XXXXXXX,X____X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  XXXXXXXX,X_X__X__,
  ___X__X_,__X__X__,
  __X___X_,_____X__,
  __X___X_,___X_X__,
  _X_____X,____X___,
  X______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_591A[ 32] = { /* code 591A */
  ______X_,________,
  ______X_,________,
  _____XXX,XXXX____,
  ____X___,__X_____,
  __XXX___,_X______,
  _____X__,X_______,
  ______XX,_X______,
  ____XX__,X_______,
  _XXX___X,XXXXX___,
  ______X_,____X___,
  ____XX__,___X____,
  __XX__X_,__X_____,
  _______X,_X______,
  _______X,X_______,
  ____XXX_,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5927[ 32] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5BC6[ 32] = { /* code 5BC6 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_____X_,__X__X__,
  ____X__X,_X______,
  __X_X___,X___X___,
  _X__X_XX,___X_X__,
  ___XXX__,___X____,
  XXX__XXX,XXXX____,
  _______X,________,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5BF9[ 32] = { /* code 5BF9 */
  ________,___X____,
  ________,___X____,
  ________,___X____,
  _XXXXXX_,___X____,
  ______X_,XXXXXXX_,
  ______X_,___X____,
  __X__X__,___X____,
  ___X_X__,X__X____,
  ____X___,_X_X____,
  ____X___,_X_X____,
  ___X_X__,___X____,
  ___X__X_,___X____,
  __X___X_,___X____,
  _X______,___X____,
  ________,_X_X____,
  ________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5C0F[ 32] = { /* code 5C0F */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___X___X,___X____,
  ___X___X,____X___,
  ___X___X,_____X__,
  __X____X,_____X__,
  __X____X,______X_,
  _X_____X,______X_,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5DE5[ 32] = { /* code 5DE5 */
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5DEE[ 32] = { /* code 5DEE */
  ____X___,__X_____,
  _____X__,_X______,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,________,
  ____X___,________,
  ___X_XXX,XXXXX___,
  __X_____,X_______,
  _X______,X_______,
  X_______,X_______,
  ___XXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXX_____,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X__X__,___X____,
  _X____X_,__X_____,
  _X_____X,XX______,
  X____XX_,__XX____,
  __XXX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5F00[ 32] = { /* code 5F00 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_5F0F[ 32] = { /* code 5F0F */
  ________,_X__X___,
  ________,_X___X__,
  ________,_X___X__,
  ________,_X______,
  XXXXXXXX,XXXXXXX_,
  ________,_X______,
  ________,_X______,
  __XXXXX_,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,__X_____,
  ____X___,__X___X_,
  ____XXXX,___X__X_,
  _XXXX___,____X_X_,
  __X_____,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_62A5[ 32] = { /* code 62A5 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,___X_X__,
  ___X___X,____X___,
  ___X___X,________,
  ___X_X_X,XXXXXX__,
  ___XX__X,_X___X__,
  __XX___X,_X___X__,
  XX_X___X,__X_X___,
  ___X___X,__X_X___,
  ___X___X,___X____,
  ___X___X,__X_X___,
  _X_X___X,_X___X__,
  __X____X,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6570[ 32] = { /* code 6570 */
  ____X___,__X_____,
  _X__X__X,__X_____,
  __X_X_X_,__X_____,
  ____X___,__XXXXX_,
  XXXXXXXX,_X___X__,
  __X_X_X_,_X___X__,
  _X__X__X,_X___X__,
  X___X___,X_X__X__,
  ___X____,__X_X___,
  XXXXXXX_,__X_X___,
  __X___X_,___X____,
  _X____X_,___X____,
  _XX__X__,__X_X___,
  ___XX___,__X_X___,
  __XX_X__,_X___X__,
  XX____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_65F6[ 32] = { /* code 65F6 */
  ________,____X___,
  ________,____X___,
  _XXXXX__,____X___,
  _X___X__,____X___,
  _X___X_X,XXXXXXX_,
  _X___X__,____X___,
  _X___X__,____X___,
  _XXXXX__,____X___,
  _X___X__,X___X___,
  _X___X__,_X__X___,
  _X___X__,_X__X___,
  _X___X__,____X___,
  _XXXXX__,____X___,
  _X___X__,____X___,
  ________,__X_X___,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6807[ 32] = { /* code 6807 */
  ___X____,________,
  ___X___X,XXXXXX__,
  ___X____,________,
  ___X____,________,
  XXXXXX__,________,
  ___X__XX,XXXXXXX_,
  __XX____,__X_____,
  __XXX___,__X_____,
  _X_X_X_X,__X_X___,
  _X_X_X_X,__X__X__,
  X__X__X_,__X__X__,
  ___X__X_,__X___X_,
  ___X_X__,__X___X_,
  ___X____,__X_____,
  ___X____,X_X_____,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6821[ 32] = { /* code 6821 */
  ___X____,_X______,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X___X,XXXXXXX_,
  XXXXXX__,________,
  ___X____,X___X___,
  __XX___X,_____X__,
  __XXX_X_,______X_,
  _X_X_X__,X___X___,
  _X_X____,X___X___,
  X__X____,_X_X____,
  ___X____,_X_X____,
  ___X____,__X_____,
  ___X____,_X_X____,
  ___X____,X___X___,
  ___X__XX,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6BD4[ 32] = { /* code 6BD4 */
  ________,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X____X__,
  __X_____,X___X___,
  __X_____,X__X____,
  __XXXXX_,X_X_____,
  __X_____,XX______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_____X_,
  __X__XX_,X_____X_,
  __XXX___,X_____X_,
  __X_____,_XXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6C14[ 32] = { /* code 6C14 */
  ___X____,________,
  ___X____,________,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  _X__XXXX,XXXX____,
  X_______,________,
  __XXXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,____X_X_,
  ________,____X_X_,
  ________,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6D41[ 32] = { /* code 6D41 */
  ________,X_______,
  __X_____,_X______,
  ___X_XXX,XXXXXXX_,
  ___X____,X_______,
  X______X,___X____,
  _X____X_,____X___,
  _X___XXX,XXXXXX__,
  ___X____,_____X__,
  ___X____,________,
  __X___X_,_X__X___,
  XXX___X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X_X_,
  __X__X__,_X__X_X_,
  ____X___,_X___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6E29[ 32] = { /* code 6E29 */
  ________,________,
  __X___XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  X_____XX,XXXXX___,
  _X____X_,____X___,
  _X____X_,____X___,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X__XXX,XXXXXX__,
  XXX__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_6EE4[ 32] = { /* code 6EE4 */
  ________,_X______,
  __X_____,_XXXXX__,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  X____X__,_X____X_,
  _X___X__,_XXX____,
  _X___XXX,XX___X__,
  ___X_X__,_X___X__,
  ___X_X__,__XXXX__,
  __X__X__,__X_____,
  XXX__X__,___X____,
  __X__X__,_X_X_X__,
  __X__X_X,_X____X_,
  __X_X__X,_X____X_,
  __X_X__X,_X__X_X_,
  ___X__X_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_70B9[ 32] = { /* code 70B9 */
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  ________,________,
  __X__X__,X___X___,
  __X___X_,_X___X__,
  _X____X_,_X___X__,
  X_______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_77AC[ 32] = { /* code 77AC */
  ________,__XXXX__,
  _____XXX,XX______,
  XXXX____,_X___X__,
  X__X__X_,__X__X__,
  X__X___X,____X___,
  XXXX_XXX,XXXXXXX_,
  X__X_X__,______X_,
  X__XX_X_,____X___,
  XXXX__X_,____X___,
  X__X__XX,X_XXXXX_,
  X__X_X__,X___X___,
  X__XX_X_,X_X_X___,
  XXXX___X,__XXXXX_,
  X__X__X_,____X___,
  _____X__,____X___,
  ____X___,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_7801[ 32] = { /* code 7801 */
  ________,________,
  _______X,XXXXX___,
  XXXXXX__,____X___,
  ___X____,____X___,
  ___X____,X___X___,
  __X_____,X___X___,
  __XXXX__,X___X___,
  _XX__X__,XXXXXXX_,
  _XX__X__,______X_,
  X_X__X__,______X_,
  __X__X__,______X_,
  __X__X_X,XXXXX_X_,
  __XXXX__,______X_,
  __X__X__,______X_,
  __X_____,___X_X__,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_7A0B[ 32] = { /* code 7A0B */
  ____X___,________,
  ___XXX_X,XXXXXX__,
  XXXX___X,_____X__,
  ___X___X,_____X__,
  ___X___X,_____X__,
  XXXXXX_X,XXXXXX__,
  ___X____,________,
  __XX____,________,
  __XXX__X,XXXXXXX_,
  _X_X_X__,__X_____,
  _X_X_X__,__X_____,
  X__X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_7C7B[ 32] = { /* code 7C7B */
  _______X,________,
  ___X___X,___X____,
  ____X__X,__X_____,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _____X_X,_X______,
  ____X__X,__X_____,
  ___X___X,___X____,
  _XX_____,____X___,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  __XX____,___XX___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_7CFB[ 32] = { /* code 7CFB */
  ________,XXXXX___,
  __XXXXXX,________,
  _____X__,________,
  ____X___,__X_____,
  ___X____,_X______,
  __XXXXXX,X_______,
  _______X,________,
  _____XX_,___X____,
  ___XX___,____X___,
  _XXXXXXX,XXXXXX__,
  _______X,_____X__,
  ____X__X,__X_____,
  ___X___X,___X____,
  __X____X,____X___,
  _X___X_X,_____X__,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_7EDF[ 32] = { /* code 7EDF */
  ___X____,_X______,
  ___X____,__X_____,
  __X_____,__X_____,
  __X___XX,XXXXXXX_,
  _X__X___,_X______,
  XXXXX___,X___X___,
  ___X___X,_____X__,
  __X___XX,XXXXXXX_,
  _X______,X__X__X_,
  XXXXX___,X__X____,
  _X______,X__X____,
  ________,X__X____,
  ___XX__X,___X__X_,
  XXX____X,___X__X_,
  _X____X_,____XXX_,
  _____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_81EA[ 32] = { /* code 81EA */
  _______X,________,
  ______X_,________,
  _____X__,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_8865[ 32] = { /* code 8865 */
  ___X____,_X______,
  ____X___,_X______,
  ________,_X______,
  _XXXXXX_,_X______,
  ______X_,_X______,
  _____X__,_XX_____,
  ____X___,_X_X____,
  ___XX_X_,_X__X___,
  __X_XX__,_X___X__,
  _X__X_X_,_X___X__,
  ____X_X_,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_89E3[ 32] = { /* code 89E3 */
  ___X____,________,
  ___X____,XXXXXX__,
  __XXXX__,__X__X__,
  __X__X__,__X__X__,
  _X__X___,_X_X_X__,
  X_XXXXX_,X___X___,
  __X_X_X_,___X____,
  __X_X_X_,_X_X____,
  __XXXXX_,_XXXXX__,
  __X_X_X_,X__X____,
  __X_X_X_,___X____,
  __XXXXX_,XXXXXXX_,
  __X_X_X_,___X____,
  _X__X_X_,___X____,
  _X____X_,___X____,
  X____XX_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_8B66[ 32] = { /* code 8B66 */
  __X__X__,__X_____,
  XXXXXXXX,__X_____,
  __X__X__,_XXXXXX_,
  _XXXXXX_,XX___X__,
  X_____X_,__X_X___,
  _XXXX_X_,___X____,
  _X__X_X_,__X_X___,
  _XXXX_X_,XX___XX_,
  _____X_X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  __XXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_8F93[ 32] = { /* code 8F93 */
  __X_____,_X______,
  __X_____,X_X_____,
  __X____X,___X____,
  XXXXX_X_,____X___,
  __X__X_X,XXXX_XX_,
  _X______,________,
  _X_X__XX,XX___X__,
  X__X__X_,_X_X_X__,
  XXXXX_X_,_X_X_X__,
  ___X__XX,XX_X_X__,
  ___XX_X_,_X_X_X__,
  XXXX__X_,_X_X_X__,
  _X_X__XX,XX_X_X__,
  ___X__X_,_X___X__,
  ___X__X_,_X_X_X__,
  ___X__X_,XX__X___};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_8FC7[ 32] = { /* code 8FC7 */
  ________,___X____,
  __X_____,___X____,
  ___X____,___X____,
  ___X_XXX,XXXXXXX_,
  ________,___X____,
  ________,___X____,
  XXXX__X_,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,_X_X____,
  ___X____,__X_____,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_901A[ 32] = { /* code 901A */
  ________,________,
  _X___XXX,XXXXX___,
  __X_____,___X____,
  __X____X,X_X_____,
  ________,_X______,
  _____XXX,XXXXXX__,
  XXX__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,_X___X__,
  __X__X__,_X___X__,
  __X__XXX,XXXXXX__,
  __X__X__,_X___X__,
  __X__X__,_X_X_X__,
  _X_X_X__,____X___,
  X___XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_9053[ 32] = { /* code 9053 */
  ______X_,____X___,
  __X____X,___X____,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  ________,X_______,
  ______XX,XXXXX___,
  XXXX__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  ___X__XX,XXXXX___,
  ___X__X_,____X___,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_91CF[ 32] = { /* code 91CF */
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  ___X___X,___X____,
  ___XXXXX,XXXX____,
  _______X,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _XXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_9501[ 32] = { /* code 9501 */
  ___X____,__X_____,
  ___X___X,__X__X__,
  __XXXX__,X_X__X__,
  __X_____,X_X_X___,
  _X______,__X_____,
  X_XXXX_X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,__X__X__,
  XXXXXX_X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___X_X__,_X_X____,
  ___XX___,X___X___,
  ___X___X,_____X__,
  ______X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_9650[ 32] = { /* code 9650 */
  ________,________,
  _XXXX_XX,XXXXX___,
  _X__X_X_,____X___,
  _X_X__X_,____X___,
  _X_X__XX,XXXXX___,
  _XX___X_,____X___,
  _X_X__X_,____X___,
  _X__X_XX,XXXXX___,
  _X__X_X_,_X___X__,
  _X__X_X_,_X__X___,
  _XX_X_X_,__XX____,
  _X_X__X_,__X_____,
  _X____X_,___X____,
  _X____X_,X___X___,
  _X____XX,_____XX_,
  _X____X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_9664[ 32] = { /* code 9664 */
  ________,_X______,
  _XXXX___,_X______,
  _X__X___,X_X_____,
  _X_X___X,___X____,
  _X_X__X_,____X___,
  _XX__X_X,XXXX_XX_,
  _X_X____,_X______,
  _X__X___,_X______,
  _X__XXXX,XXXXXX__,
  _X__X___,_X______,
  _XX_X_X_,_X_X____,
  _X_X__X_,_X__X___,
  _X___X__,_X___X__,
  _X__X___,_X___X__,
  _X_____X,_X______,
  _X______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_96F6[ 32] = { /* code 96F6 */
  __XXXXXX,XXXXX___,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X_____X,______X_,
  X__XXX_X,_XXX_X__,
  _______X,________,
  ___XXX_X,_XXX____,
  ______X_,X_______,
  ____XX__,_XX_____,
  __XX__X_,___XX___,
  XX_____X,_____XX_,
  ___XXXXX,XXX_____,
  ________,__X_____,
  _____XX_,_X______,
  _______X,X_______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontST16_9879[ 32] = { /* code 9879 */
  ________,________,
  _______X,XXXXXXX_,
  ________,__X_____,
  XXXXXX__,_X______,
  ___X___X,XXXXXX__,
  ___X___X,_____X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  ___XXX_X,_X___X__,
  XXX_____,_X_X____,
  _X______,X___X___,
  _______X,_____X__,
  ______X_,______X_};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_CONST_STORAGE unsigned char acGUI_FontST16_FF0C[ 32] = { /* code FF0C, FULLWIDTH COMMA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XX____,________,
  __XX____,________,
  ___X____,________,
  __X_____,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontST16_CharInfo[102] = {
   {   8,   8,  1, acGUI_FontST16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_FontST16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_FontST16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_FontST16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_FontST16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_FontST16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_FontST16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_FontST16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_FontST16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_FontST16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_FontST16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_FontST16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_FontST16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_FontST16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_FontST16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_FontST16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_FontST16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_FontST16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontST16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontST16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontST16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_FontST16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_FontST16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontST16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontST16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_FontST16_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_FontST16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_FontST16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_FontST16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_FontST16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_FontST16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_FontST16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_FontST16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_FontST16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_FontST16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_FontST16_0078 } /* code 0078 */
  ,{  16,  16,  2, acGUI_FontST16_00B0 } /* code 00B0 */
  ,{   8,   8,  1, acGUI_FontST16_00B2 } /* code 00B2 */
  ,{   8,   8,  1, acGUI_FontST16_00B3 } /* code 00B3 */
  ,{  16,  16,  2, acGUI_FontST16_2103 } /* code 2103 */
  ,{  16,  16,  2, acGUI_FontST16_2211 } /* code 2211 */
  ,{  16,  16,  2, acGUI_FontST16_25B3 } /* code 25B3 */
  ,{  16,  16,  2, acGUI_FontST16_4E0A } /* code 4E0A */
  ,{  16,  16,  2, acGUI_FontST16_4E0B } /* code 4E0B */
  ,{  16,  16,  2, acGUI_FontST16_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_FontST16_4F8B } /* code 4F8B */
  ,{  16,  16,  2, acGUI_FontST16_4FE1 } /* code 4FE1 */
  ,{  16,  16,  2, acGUI_FontST16_503C } /* code 503C */
  ,{  16,  16,  2, acGUI_FontST16_507F } /* code 507F */
  ,{  16,  16,  2, acGUI_FontST16_5165 } /* code 5165 */
  ,{  16,  16,  2, acGUI_FontST16_51B5 } /* code 51B5 */
  ,{  16,  16,  2, acGUI_FontST16_51C6 } /* code 51C6 */
  ,{  16,  16,  2, acGUI_FontST16_51FA } /* code 51FA */
  ,{  16,  16,  2, acGUI_FontST16_5207 } /* code 5207 */
  ,{  16,  16,  2, acGUI_FontST16_529B } /* code 529B */
  ,{  16,  16,  2, acGUI_FontST16_52A8 } /* code 52A8 */
  ,{  16,  16,  2, acGUI_FontST16_5355 } /* code 5355 */
  ,{  16,  16,  2, acGUI_FontST16_538B } /* code 538B */
  ,{  16,  16,  2, acGUI_FontST16_53F7 } /* code 53F7 */
  ,{  16,  16,  2, acGUI_FontST16_578B } /* code 578B */
  ,{  16,  16,  2, acGUI_FontST16_591A } /* code 591A */
  ,{  16,  16,  2, acGUI_FontST16_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_FontST16_5BC6 } /* code 5BC6 */
  ,{  16,  16,  2, acGUI_FontST16_5BF9 } /* code 5BF9 */
  ,{  16,  16,  2, acGUI_FontST16_5C0F } /* code 5C0F */
  ,{  16,  16,  2, acGUI_FontST16_5DE5 } /* code 5DE5 */
  ,{  16,  16,  2, acGUI_FontST16_5DEE } /* code 5DEE */
  ,{  16,  16,  2, acGUI_FontST16_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_FontST16_5F00 } /* code 5F00 */
  ,{  16,  16,  2, acGUI_FontST16_5F0F } /* code 5F0F */
  ,{  16,  16,  2, acGUI_FontST16_62A5 } /* code 62A5 */
  ,{  16,  16,  2, acGUI_FontST16_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_FontST16_65F6 } /* code 65F6 */
  ,{  16,  16,  2, acGUI_FontST16_6807 } /* code 6807 */
  ,{  16,  16,  2, acGUI_FontST16_6821 } /* code 6821 */
  ,{  16,  16,  2, acGUI_FontST16_6BD4 } /* code 6BD4 */
  ,{  16,  16,  2, acGUI_FontST16_6C14 } /* code 6C14 */
  ,{  16,  16,  2, acGUI_FontST16_6D41 } /* code 6D41 */
  ,{  16,  16,  2, acGUI_FontST16_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_FontST16_6EE4 } /* code 6EE4 */
  ,{  16,  16,  2, acGUI_FontST16_70B9 } /* code 70B9 */
  ,{  16,  16,  2, acGUI_FontST16_77AC } /* code 77AC */
  ,{  16,  16,  2, acGUI_FontST16_7801 } /* code 7801 */
  ,{  16,  16,  2, acGUI_FontST16_7A0B } /* code 7A0B */
  ,{  16,  16,  2, acGUI_FontST16_7C7B } /* code 7C7B */
  ,{  16,  16,  2, acGUI_FontST16_7CFB } /* code 7CFB */
  ,{  16,  16,  2, acGUI_FontST16_7EDF } /* code 7EDF */
  ,{  16,  16,  2, acGUI_FontST16_81EA } /* code 81EA */
  ,{  16,  16,  2, acGUI_FontST16_8865 } /* code 8865 */
  ,{  16,  16,  2, acGUI_FontST16_89E3 } /* code 89E3 */
  ,{  16,  16,  2, acGUI_FontST16_8B66 } /* code 8B66 */
  ,{  16,  16,  2, acGUI_FontST16_8F93 } /* code 8F93 */
  ,{  16,  16,  2, acGUI_FontST16_8FC7 } /* code 8FC7 */
  ,{  16,  16,  2, acGUI_FontST16_901A } /* code 901A */
  ,{  16,  16,  2, acGUI_FontST16_9053 } /* code 9053 */
  ,{  16,  16,  2, acGUI_FontST16_91CF } /* code 91CF */
  ,{  16,  16,  2, acGUI_FontST16_9501 } /* code 9501 */
  ,{  16,  16,  2, acGUI_FontST16_9650 } /* code 9650 */
  ,{  16,  16,  2, acGUI_FontST16_9664 } /* code 9664 */
  ,{  16,  16,  2, acGUI_FontST16_96F6 } /* code 96F6 */
  ,{  16,  16,  2, acGUI_FontST16_9879 } /* code 9879 */
  ,{  16,  16,  2, acGUI_FontST16_FF0C } /* code FF0C */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop81 = {
   0xFF0C /* first character */
  ,0xFF0C /* last character  */
  ,&GUI_FontST16_CharInfo[101] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop80 = {
   0x9879 /* first character */
  ,0x9879 /* last character  */
  ,&GUI_FontST16_CharInfo[100] /* address of first character */
  ,&GUI_FontST16_Prop81 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop79 = {
   0x96F6 /* first character */
  ,0x96F6 /* last character  */
  ,&GUI_FontST16_CharInfo[ 99] /* address of first character */
  ,&GUI_FontST16_Prop80 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop78 = {
   0x9664 /* first character */
  ,0x9664 /* last character  */
  ,&GUI_FontST16_CharInfo[ 98] /* address of first character */
  ,&GUI_FontST16_Prop79 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop77 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontST16_CharInfo[ 97] /* address of first character */
  ,&GUI_FontST16_Prop78 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop76 = {
   0x9501 /* first character */
  ,0x9501 /* last character  */
  ,&GUI_FontST16_CharInfo[ 96] /* address of first character */
  ,&GUI_FontST16_Prop77 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop75 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontST16_CharInfo[ 95] /* address of first character */
  ,&GUI_FontST16_Prop76 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop74 = {
   0x9053 /* first character */
  ,0x9053 /* last character  */
  ,&GUI_FontST16_CharInfo[ 94] /* address of first character */
  ,&GUI_FontST16_Prop75 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop73 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_FontST16_CharInfo[ 93] /* address of first character */
  ,&GUI_FontST16_Prop74 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop72 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontST16_CharInfo[ 92] /* address of first character */
  ,&GUI_FontST16_Prop73 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop71 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontST16_CharInfo[ 91] /* address of first character */
  ,&GUI_FontST16_Prop72 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop70 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontST16_CharInfo[ 90] /* address of first character */
  ,&GUI_FontST16_Prop71 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop69 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_FontST16_CharInfo[ 89] /* address of first character */
  ,&GUI_FontST16_Prop70 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop68 = {
   0x8865 /* first character */
  ,0x8865 /* last character  */
  ,&GUI_FontST16_CharInfo[ 88] /* address of first character */
  ,&GUI_FontST16_Prop69 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop67 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontST16_CharInfo[ 87] /* address of first character */
  ,&GUI_FontST16_Prop68 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop66 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontST16_CharInfo[ 86] /* address of first character */
  ,&GUI_FontST16_Prop67 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop65 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontST16_CharInfo[ 85] /* address of first character */
  ,&GUI_FontST16_Prop66 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop64 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontST16_CharInfo[ 84] /* address of first character */
  ,&GUI_FontST16_Prop65 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop63 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontST16_CharInfo[ 83] /* address of first character */
  ,&GUI_FontST16_Prop64 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop62 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_FontST16_CharInfo[ 82] /* address of first character */
  ,&GUI_FontST16_Prop63 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop61 = {
   0x77AC /* first character */
  ,0x77AC /* last character  */
  ,&GUI_FontST16_CharInfo[ 81] /* address of first character */
  ,&GUI_FontST16_Prop62 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop60 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontST16_CharInfo[ 80] /* address of first character */
  ,&GUI_FontST16_Prop61 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop59 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_FontST16_CharInfo[ 79] /* address of first character */
  ,&GUI_FontST16_Prop60 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop58 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontST16_CharInfo[ 78] /* address of first character */
  ,&GUI_FontST16_Prop59 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop57 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontST16_CharInfo[ 77] /* address of first character */
  ,&GUI_FontST16_Prop58 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop56 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_FontST16_CharInfo[ 76] /* address of first character */
  ,&GUI_FontST16_Prop57 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop55 = {
   0x6BD4 /* first character */
  ,0x6BD4 /* last character  */
  ,&GUI_FontST16_CharInfo[ 75] /* address of first character */
  ,&GUI_FontST16_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop54 = {
   0x6821 /* first character */
  ,0x6821 /* last character  */
  ,&GUI_FontST16_CharInfo[ 74] /* address of first character */
  ,&GUI_FontST16_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop53 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontST16_CharInfo[ 73] /* address of first character */
  ,&GUI_FontST16_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop52 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontST16_CharInfo[ 72] /* address of first character */
  ,&GUI_FontST16_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop51 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontST16_CharInfo[ 71] /* address of first character */
  ,&GUI_FontST16_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop50 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontST16_CharInfo[ 70] /* address of first character */
  ,&GUI_FontST16_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop49 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontST16_CharInfo[ 69] /* address of first character */
  ,&GUI_FontST16_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop48 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontST16_CharInfo[ 68] /* address of first character */
  ,&GUI_FontST16_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop47 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontST16_CharInfo[ 67] /* address of first character */
  ,&GUI_FontST16_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop46 = {
   0x5DEE /* first character */
  ,0x5DEE /* last character  */
  ,&GUI_FontST16_CharInfo[ 66] /* address of first character */
  ,&GUI_FontST16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop45 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontST16_CharInfo[ 65] /* address of first character */
  ,&GUI_FontST16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop44 = {
   0x5C0F /* first character */
  ,0x5C0F /* last character  */
  ,&GUI_FontST16_CharInfo[ 64] /* address of first character */
  ,&GUI_FontST16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop43 = {
   0x5BF9 /* first character */
  ,0x5BF9 /* last character  */
  ,&GUI_FontST16_CharInfo[ 63] /* address of first character */
  ,&GUI_FontST16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop42 = {
   0x5BC6 /* first character */
  ,0x5BC6 /* last character  */
  ,&GUI_FontST16_CharInfo[ 62] /* address of first character */
  ,&GUI_FontST16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop41 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_FontST16_CharInfo[ 61] /* address of first character */
  ,&GUI_FontST16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop40 = {
   0x591A /* first character */
  ,0x591A /* last character  */
  ,&GUI_FontST16_CharInfo[ 60] /* address of first character */
  ,&GUI_FontST16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop39 = {
   0x578B /* first character */
  ,0x578B /* last character  */
  ,&GUI_FontST16_CharInfo[ 59] /* address of first character */
  ,&GUI_FontST16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop38 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontST16_CharInfo[ 58] /* address of first character */
  ,&GUI_FontST16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop37 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontST16_CharInfo[ 57] /* address of first character */
  ,&GUI_FontST16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop36 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontST16_CharInfo[ 56] /* address of first character */
  ,&GUI_FontST16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop35 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontST16_CharInfo[ 55] /* address of first character */
  ,&GUI_FontST16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop34 = {
   0x529B /* first character */
  ,0x529B /* last character  */
  ,&GUI_FontST16_CharInfo[ 54] /* address of first character */
  ,&GUI_FontST16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop33 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_FontST16_CharInfo[ 53] /* address of first character */
  ,&GUI_FontST16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop32 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontST16_CharInfo[ 52] /* address of first character */
  ,&GUI_FontST16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop31 = {
   0x51C6 /* first character */
  ,0x51C6 /* last character  */
  ,&GUI_FontST16_CharInfo[ 51] /* address of first character */
  ,&GUI_FontST16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop30 = {
   0x51B5 /* first character */
  ,0x51B5 /* last character  */
  ,&GUI_FontST16_CharInfo[ 50] /* address of first character */
  ,&GUI_FontST16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop29 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontST16_CharInfo[ 49] /* address of first character */
  ,&GUI_FontST16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop28 = {
   0x507F /* first character */
  ,0x507F /* last character  */
  ,&GUI_FontST16_CharInfo[ 48] /* address of first character */
  ,&GUI_FontST16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop27 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontST16_CharInfo[ 47] /* address of first character */
  ,&GUI_FontST16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop26 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontST16_CharInfo[ 46] /* address of first character */
  ,&GUI_FontST16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop25 = {
   0x4F8B /* first character */
  ,0x4F8B /* last character  */
  ,&GUI_FontST16_CharInfo[ 45] /* address of first character */
  ,&GUI_FontST16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop24 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontST16_CharInfo[ 44] /* address of first character */
  ,&GUI_FontST16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop23 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_FontST16_CharInfo[ 42] /* address of first character */
  ,&GUI_FontST16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop22 = {
   0x25B3 /* first character */
  ,0x25B3 /* last character  */
  ,&GUI_FontST16_CharInfo[ 41] /* address of first character */
  ,&GUI_FontST16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop21 = {
   0x2211 /* first character */
  ,0x2211 /* last character  */
  ,&GUI_FontST16_CharInfo[ 40] /* address of first character */
  ,&GUI_FontST16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop20 = {
   0x2103 /* first character */
  ,0x2103 /* last character  */
  ,&GUI_FontST16_CharInfo[ 39] /* address of first character */
  ,&GUI_FontST16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop19 = {
   0x00B2 /* first character */
  ,0x00B3 /* last character  */
  ,&GUI_FontST16_CharInfo[ 37] /* address of first character */
  ,&GUI_FontST16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop18 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontST16_CharInfo[ 36] /* address of first character */
  ,&GUI_FontST16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop17 = {
   0x0078 /* first character */
  ,0x0078 /* last character  */
  ,&GUI_FontST16_CharInfo[ 35] /* address of first character */
  ,&GUI_FontST16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop16 = {
   0x0074 /* first character */
  ,0x0074 /* last character  */
  ,&GUI_FontST16_CharInfo[ 34] /* address of first character */
  ,&GUI_FontST16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop15 = {
   0x0072 /* first character */
  ,0x0072 /* last character  */
  ,&GUI_FontST16_CharInfo[ 33] /* address of first character */
  ,&GUI_FontST16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop14 = {
   0x0070 /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontST16_CharInfo[ 32] /* address of first character */
  ,&GUI_FontST16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop13 = {
   0x006B /* first character */
  ,0x006D /* last character  */
  ,&GUI_FontST16_CharInfo[ 29] /* address of first character */
  ,&GUI_FontST16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop12 = {
   0x0067 /* first character */
  ,0x0067 /* last character  */
  ,&GUI_FontST16_CharInfo[ 28] /* address of first character */
  ,&GUI_FontST16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop11 = {
   0x0061 /* first character */
  ,0x0062 /* last character  */
  ,&GUI_FontST16_CharInfo[ 26] /* address of first character */
  ,&GUI_FontST16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop10 = {
   0x005E /* first character */
  ,0x005E /* last character  */
  ,&GUI_FontST16_CharInfo[ 25] /* address of first character */
  ,&GUI_FontST16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop9 = {
   0x0058 /* first character */
  ,0x0058 /* last character  */
  ,&GUI_FontST16_CharInfo[ 24] /* address of first character */
  ,&GUI_FontST16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop8 = {
   0x0054 /* first character */
  ,0x0054 /* last character  */
  ,&GUI_FontST16_CharInfo[ 23] /* address of first character */
  ,&GUI_FontST16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop7 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontST16_CharInfo[ 22] /* address of first character */
  ,&GUI_FontST16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop6 = {
   0x004D /* first character */
  ,0x004D /* last character  */
  ,&GUI_FontST16_CharInfo[ 21] /* address of first character */
  ,&GUI_FontST16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop5 = {
   0x004B /* first character */
  ,0x004B /* last character  */
  ,&GUI_FontST16_CharInfo[ 20] /* address of first character */
  ,&GUI_FontST16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop4 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontST16_CharInfo[ 19] /* address of first character */
  ,&GUI_FontST16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop3 = {
   0x0042 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_FontST16_CharInfo[ 17] /* address of first character */
  ,&GUI_FontST16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop2 = {
   0x002B /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontST16_CharInfo[  1] /* address of first character */
  ,&GUI_FontST16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontST16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontST16_CharInfo[  0] /* address of first character */
  ,&GUI_FontST16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontST16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontST16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

