/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
 #include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x04)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x06)
#define ID_LISTBOX_1 (GUI_ID_USER + 0x07)
#define ID_LISTBOX_2 (GUI_ID_USER + 0x08)
#define ID_LISTBOX_3 (GUI_ID_USER + 0x09)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  {LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 16, 64, 50, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_1, 64, 16, 32, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_2, 64, 32, 32, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_3, 64, 48, 32, 16, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  uint8_t arr1[][10]={"Pa","KPa","MPa","KgF","Bar"};
  uint8_t i;
  static WM_HWIN hWin_v[5];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"输入单位");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "差压单位");
    LISTBOX_AddString(hItem, "压力单位");
    LISTBOX_AddString(hItem, "温度单位");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1);
    for(i=0;i<sizeof(arr1)/sizeof(arr1[0]);i++)
    {
        LISTBOX_AddString(hItem, arr1[i]);
    }
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_2);
    for(i=0;i<sizeof(arr1)/sizeof(arr1[0]);i++)
    {
        LISTBOX_AddString(hItem, arr1[i]);
    }
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_3);
    LISTBOX_AddString(hItem, "°C");
    LISTBOX_AddString(hItem, "K");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    for(i=0;i<4;i++)
    {
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0+i);
    }
    LISTBOX_SetSel(hWin_v[1],tongdao.Uint[0]);
    LISTBOX_SetSel(hWin_v[2],tongdao.Uint[1]);
    LISTBOX_SetSel(hWin_v[3],tongdao.Uint[2]);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_1: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_2: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
    case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1+LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))));
            }
            else if(hItem==hWin_v[1])
            {
                tongdao.Uint[0]=LISTBOX_GetSel(hWin_v[1]);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
            }
            else if(hItem==hWin_v[2])
            {
                tongdao.Uint[1]=LISTBOX_GetSel(hWin_v[2]);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
            }
            else if(hItem==hWin_v[3])
            {
                tongdao.Uint[2]=LISTBOX_GetSel(hWin_v[3]);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
            }

        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            WM_DeleteWindow(pMsg->hWin);
            Tongdao();
            }
        }
        WM_DefaultProc(pMsg);
        break;
  }
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Tongdao12(void);
WM_HWIN Tongdao12(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
