/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x03)
#define ID_LISTBOX_1 (GUI_ID_USER + 0x04)
#define ID_TEXT_2 (GUI_ID_USER + 0x05)
#define ID_EDIT_0 (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 30, 0, 32, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 62, 0, 66, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 16, 40, 50, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_1, 60, 16, 40, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 40, 32, 88, 16, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 40, 48, 88, 16, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static WM_HWIN hWin_v[5];
  uint8_t i;
  uint8_t ch[20];
  static float R=0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"压力");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    sprintf(ch,"%3.4f",measure.YL);
    TEXT_SetText(hItem,ch);
    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "模式");
    LISTBOX_AddString(hItem, "校准");
    LISTBOX_AddString(hItem, "微调");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1);
    LISTBOX_AddString(hItem, "0MA");
    LISTBOX_AddString(hItem, "4MA");
    LISTBOX_AddString(hItem, "20MA");
    LISTBOX_SetSel(hItem,jiaodui.Mode[1]);
    LISTBOX_SetFont(hItem, GUI_FONT_16_ASCII);
    LISTBOX_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	sprintf(ch,"%2.3f",measure.V[1]/system.R[1]);
    TEXT_SetText(hItem,ch);
    TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFloatMode(hItem,jiaodui.Move[1],0,2,4,GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFloatValue(hItem,jiaodui.Move[1]);
    EDIT_EnableBlink(hItem,500,1);
    EDIT_SetCursorAtChar(hItem,5);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    R=system.R[1];
    for(i=0;i<5;i++)
    	hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_TEXT_1+i);
    WM_CreateTimer(pMsg->hWin,0x01,200,0);
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v,1000);
    system.R[1]=R*jiaodui.Move[1];
    sprintf(ch,"%.4f",measure.YL);
    TEXT_SetText(hWin_v[0],ch);
    sprintf(ch,"%2.3f",measure.V[1]/system.R[1]*1000);
    TEXT_SetText(hWin_v[3],ch);




break;
case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[1])
            {
                i=LISTBOX_GetSel(hWin_v[1]);
                switch (i)
                {
                	case 0:
                	WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1));
                	break;
                	case 1:
                    {
                        jiaodui.Move[1]=1;
                        EDIT_SetFloatValue(hWin_v[4],2-jiaodui.Move[1]);
                        switch(jiaodui.Mode[1])
                        {

                            case 0:R=160;break;
                            case 1:R=measure.V[1]/0.004;break;
                            case 2:R=measure.V[1]/0.020;break;
                        }
                    }
                	break;
                	case 2:
                	WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
                	break;
                }
            }
            else if(hItem==hWin_v[2])
            {
                jiaodui.Mode[1]=LISTBOX_GetSel(hWin_v[2]);
                WM_SetFocus(hWin_v[1]);
            }
            else if(hItem==hWin_v[4])
            {
                jiaodui.Move[1]=2-EDIT_GetFloatValue(hWin_v[4]);
                WM_SetFocus(hWin_v[1]);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[1])
            {
            WM_DeleteWindow(pMsg->hWin);
            Jiaodui();
            }
        }
        WM_DefaultProc(pMsg);
        break;
  }
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Jiaodui2(void);
WM_HWIN Jiaodui2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
