/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
#define ID_TEXT_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_11 (GUI_ID_USER + 0x0C)
// USER START (Optionally insert additional defines)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0D)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern WM_HWIN Menu_lock(void);
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
#define T0      273.15
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 16, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 16, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 32, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 0, 48, 32, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 17, 0, 88, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 32, 16, 72, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 32, 32, 72, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 32, 48, 72, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 103, 0, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 103, 16, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 103, 32, 24, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 103, 48, 24, 16, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 65, 1, 1, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char temp[20];
  static uint8_t times,mark1=1;
  uint8_t unit1[][10]={"Pa","KPa","MPa","KgF","Bar"};
  uint8_t unit2[][5]={"°C","K"};
  uint8_t unit3[][5]={"Kg/s","t/s","l/s","m3/s","Kg/m","t/m","l/m","m3/m","Kg/h","t/h","l/h","m3/h"};
  uint8_t unit4[][5]={"Kg","t","l","m³"};
  uint8_t i;
  static WM_HWIN hWin_v[15];
  // USER END

  switch (pMsg->MsgId) {
      case WM_INIT_DIALOG:
            for(i=0;i<12;i++)
                hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_TEXT_0+i);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
            TEXT_SetText(hItem, "∑");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
            TEXT_SetText(hItem, "瞬时");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
            if(mark1==1)
                TEXT_SetText(hItem, "差压");
            else
                TEXT_SetText(hItem, "压力");
            TEXT_SetFont(hItem, &GUI_FontST16);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
            TEXT_SetText(hItem, "温度");
            TEXT_SetFont(hItem, &GUI_FontST16);
            // Initialization of 'Text'
            //
            for(i=0;i<4;i++)
            {
                TEXT_SetFont(hWin_v[4+i], GUI_FONT_8_ASCII);
                TEXT_SetTextAlign(hWin_v[4+i], GUI_TA_RIGHT|GUI_TA_VCENTER);
            }
            sprintf(temp,"%15.3f",measure.EF_S);
            TEXT_SetText(hWin_v[4], temp);
            measure.F_S=0;
            sprintf(temp,"%12.3f",measure.F_S);
            TEXT_SetText(hWin_v[5], temp);
            measure.CY=0;
            measure.YL=0;
            if(!mark1)
                sprintf(temp,"%12.4f",measure.CY);
            else
                sprintf(temp,"%12.4f",measure.YL);
            TEXT_SetText(hWin_v[6], temp);
            sprintf(temp,"%7.2f",measure.T_S);
            TEXT_SetText(hWin_v[7], temp);

            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
            TEXT_SetText(hItem, unit4[tongdao.Unit[4]]);
            TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
            TEXT_SetFont(hItem, GUI_FONT_8_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            TEXT_SetText(hItem, unit3[tongdao.Unit[3]]);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
            TEXT_SetFont(hItem, GUI_FONT_13_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            TEXT_SetText(hItem, unit1[tongdao.Unit[0]]);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
            TEXT_SetFont(hItem, &GUI_FontST16);
            TEXT_SetText(hItem, unit2[tongdao.Unit[2]]);
            TEXT_SetTextAlign(hItem, GUI_TA_RIGHT|GUI_TA_VCENTER);
            // USER START (Optionally insert additional code for further widget initialization)
            WM_CreateTimer(pMsg->hWin,0x01,20,0);
            WM_CreateTimer(pMsg->hWin,0x02,40,0);

            // USER END
        break;
  // USER START (Optionally insert additional message handling)
    case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_DeleteWindow(pMsg->hWin);
        Menu_lock();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
      case WM_TIMER:
        switch(WM_GetTimerId(pMsg->Data.v))
        {
            case 1:
                    WM_RestartTimer(pMsg->Data.v,2000);
                    sprintf(temp,"%15.3f",measure.EF_S);
                    TEXT_SetText(hWin_v[4], temp);
                    sprintf(temp,"%12.3f",measure.F_S);
                    //sprintf(temp,"%d",GUI_ALLOC_GetMaxUsedBytes());
                    TEXT_SetText(hWin_v[5], temp);
                    if(!mark1)
                        sprintf(temp,"%12.4f",measure.CY);
                    else
                        sprintf(temp,"%12.4f",measure.YL);
                    TEXT_SetText(hWin_v[6], temp);
                    sprintf(temp,"%7.2f",measure.T_S);
                    //sprintf(temp,"%d",GUI_ALLOC_GetNumFreeBytes());
                    TEXT_SetText(hWin_v[7], temp);
                break;
            case 2:
                {
                    WM_RestartTimer(pMsg->Data.v,4000);
                    if((measure.MODE)>>1&0x01)
                    {
                         if(mark1==0)
                        {
                            TEXT_SetText(hWin_v[2], "压力");
                            TEXT_SetText(hWin_v[10], unit1[tongdao.Unit[1]]);
                            mark1=1;
                        }
                        else
                        {
                            TEXT_SetText(hWin_v[2], "差压");
                            TEXT_SetText(hWin_v[10], unit1[tongdao.Unit[0]]);
                            mark1=0;
                        }
                    }
                    else
                    {
                        mark1=0;
                        TEXT_SetText(hWin_v[2], "差压");
                        TEXT_SetText(hWin_v[10], unit1[tongdao.Unit[0]]);
                    }
                    if(!mark1)
                        sprintf(temp,"%12.4f",measure.CY);
                    else
                        sprintf(temp,"%12.4f",measure.YL);
                    TEXT_SetText(hWin_v[6], temp);
                }
                break;
        }

      break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Main_status(void);
WM_HWIN Main_status(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
