/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x02)
#define ID_LISTBOX_1 (GUI_ID_USER + 0x03)
#define ID_LISTBOX_2 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 16, 40, 50, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_1, 40, 16, 80, 17, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_2, 40, 32, 80, 16, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static WM_HWIN hWin_v[5];
  uint8_t i;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"电流输出");
    TEXT_SetFont(hItem,&GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "开关");
    LISTBOX_AddString(hItem, "模式");
    LISTBOX_SetFont(hItem,&GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1);
    LISTBOX_AddString(hItem, "关");
    LISTBOX_AddString(hItem, "开");
    LISTBOX_SetFont(hItem,&GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTBOX_SetSel(hItem,shuchu.OnOff[0]);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_2);
    LISTBOX_AddString(hItem, "4-20MA");
    LISTBOX_AddString(hItem, "0-20MA");
    LISTBOX_SetFont(hItem,GUI_FONT_16_ASCII);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTBOX_SetSel(hItem,shuchu.Mode[0]);
    // USER START (Optionally insert additional code for further widget initialization)
    for(i=0;i<3;i++)
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0+i);
    // USER END
    break;
    // USER START (Optionally insert additional code for further Ids)

    // USER END
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
                i=LISTBOX_GetSel(hWin_v[0]);
                hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1+i);
                WM_SetFocus(hItem);
            }
            else if(hItem==hWin_v[1])
            {
                shuchu.OnOff[0]=LISTBOX_GetSel(hWin_v[1]);
                WM_SetFocus(hWin_v[0]);
            }
            else if(hItem==hWin_v[2])
            {
                shuchu.Mode[0]=LISTBOX_GetSel(hWin_v[2]);
                WM_SetFocus(hWin_v[0]);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            WM_DeleteWindow(pMsg->hWin);
            Shuchu();
            }
        }
        WM_DefaultProc(pMsg);
        break;
  }
  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Shuchu2(void);
WM_HWIN Shuchu2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
