/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
 #include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x04)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x06)
#define ID_LISTBOX_1 (GUI_ID_USER + 0x07)
#define ID_LISTBOX_2 (GUI_ID_USER + 0x08)
#define ID_LISTBOX_3 (GUI_ID_USER + 0x09)
#define ID_LISTBOX_4 (GUI_ID_USER + 0x0A)
#define ID_LISTBOX_5 (GUI_ID_USER + 0x0B)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 15, 0, 0x0, 0 },
  {LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 15, 70, 50, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_1, 70, 15, 58, 17, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_2, 70, 31, 58, 17, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_3, 70, 47, 58, 17, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_4, 70, (31+50), 58, 17, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_5, 70, (47+60), 58, 17, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static uint8_t listbox_offset=0;
  static uint8_t listbox_position=0;
  static uint8_t listbox_position_s=0;
  uint8_t unit1[][10]={"Pa","KPa","MPa","KgF","Bar"};
  uint8_t unit2[][5]={"°C","K"};
  uint8_t unit3[][5]={"Kg/s","t/s","l/s","m3/s","Kg/m","t/m","l/m","m3/m","Kg/h","t/h","l/h","m3/h"};
  uint8_t unit4[][5]={"Kg","t","l","m³"};
  uint8_t i,j=0,ch[20];
  static WM_HWIN hWin_v[10];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"输入单位");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "差压单位");
    LISTBOX_AddString(hItem, "压力单位");
    LISTBOX_AddString(hItem, "温度单位");
    LISTBOX_AddString(hItem, "瞬时单位");
    LISTBOX_AddString(hItem, "累计单位");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1);
    for(i=0;i<sizeof(unit1)/sizeof(unit1[0]);i++)
        LISTBOX_AddString(hItem, unit1[i]);
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_2);
    for(i=0;i<sizeof(unit1)/sizeof(unit1[0]);i++)
        LISTBOX_AddString(hItem, unit1[i]);
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_3);
    LISTBOX_AddString(hItem, "°C");
    LISTBOX_AddString(hItem, "K");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    for(i=0;i<6;i++)
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0+i);
    for(i=0;i<sizeof(unit3)/sizeof(unit3[0]);i++)
        LISTBOX_AddString(hWin_v[4], unit3[i]);
    LISTBOX_SetFont(hWin_v[4], &GUI_FontST16);
    LISTBOX_SetTextAlign(hWin_v[4],GUI_TA_HCENTER | GUI_TA_VCENTER);

     for(i=0;i<sizeof(unit4)/sizeof(unit4[0]);i++)
        LISTBOX_AddString(hWin_v[5], unit4[i]);
    LISTBOX_SetFont(hWin_v[5], &GUI_FontST16);
    LISTBOX_SetTextAlign(hWin_v[5],GUI_TA_HCENTER | GUI_TA_VCENTER);

    LISTBOX_SetSel(hWin_v[1],tongdao.Unit[0]);
    LISTBOX_SetSel(hWin_v[2],tongdao.Unit[1]);
    LISTBOX_SetSel(hWin_v[3],tongdao.Unit[2]);
    LISTBOX_SetSel(hWin_v[4],tongdao.Unit[3]);
    LISTBOX_SetSel(hWin_v[5],tongdao.Unit[4]);

    listbox_offset=0;
    listbox_position=0;
    listbox_position_s=0;
    //WM_CreateTimer(pMsg->hWin,0x01,100,0);
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
    WM_RestartTimer(pMsg->Data.v,100);
      break;
    case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
                WM_SetFocus(hWin_v[LISTBOX_GetSel(hWin_v[0])+1]);
            }
            else
            {
                tongdao.Unit[LISTBOX_GetSel(hWin_v[0])]=LISTBOX_GetSel(hItem);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            WM_DeleteWindow(pMsg->hWin);
            Tongdao();
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_UP:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            	listbox_position_s=listbox_position;
                if(listbox_offset>0)
                    listbox_offset--;
                listbox_position=LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))-listbox_offset;
                if(listbox_position_s!=listbox_position)
                {
                    for(i=0;i<5;i++)
                    {
                        if((i>=listbox_position)&&(i<=listbox_position+2))
                            WM_MoveTo(hWin_v[i+1],70, 15+16*j++);
                        else
                            WM_MoveTo(hWin_v[i+1],170, 15+16*i);
                        LISTBOX_SetSel(hWin_v[i+1],tongdao.Unit[i]);
                    }
                }
            }
            else if(hItem==hWin_v[1]);
            else if(hItem==hWin_v[2]);
            else if(hItem==hWin_v[3]);
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_DOWN:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            	listbox_position_s=listbox_position;
                if(listbox_offset<2)
                    listbox_offset++;
                listbox_position=LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))-listbox_offset;
                if(listbox_position_s!=listbox_position)
                {
                    for(i=0;i<5;i++)
                    {
                        if((i>=listbox_position)&&(i<=listbox_position+2))
                            WM_MoveTo(hWin_v[i+1],70, 15+16*j++);
                        else
                            WM_MoveTo(hWin_v[i+1],170, 15+16*i);
                        LISTBOX_SetSel(hWin_v[i+1],tongdao.Unit[i]);
                    }
                }
            }
            else if(hItem==hWin_v[1]);
            else if(hItem==hWin_v[2]);
            else if(hItem==hWin_v[3]);
        }
        WM_DefaultProc(pMsg);
        break;
  }
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Tongdao2(void);
WM_HWIN Tongdao2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
