/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
 #include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 16, 128, 34, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 48, 128, 16, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char words[20];
  uint8_t Number;
  int i;
  uint16_t time[3]={0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem,"掉电记录");
    TEXT_SetFont(hItem, &GUI_FontST16);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    //system.PVD_Number=4;
    //system.PVD_flag=0;
    //for(i=0;i<8;i++)
    //    PVD_stack[i][0].D=i;
    if(system.PVD_flag==0)
    {
        if(system.PVD_Number==0)
        {
            Number=0;
            for(i=0;i<8;i++)
            {
                LISTBOX_AddString(hItem, "None");
            }
        }

        else
        {
            Number=system.PVD_Number-1;
            for(i=Number;i>=0;i--)
            {
                sprintf(words,"%d%02d%02d.%02d:%02d-%02d%02d.%02d:%02d"\
                    ,PVD_stack[i][1].Y,PVD_stack[i][0].M,PVD_stack[i][0].D,PVD_stack[i][0].h,PVD_stack[i][0].m\
                    ,PVD_stack[i][1].M,PVD_stack[i][1].D,PVD_stack[i][1].h,PVD_stack[i][1].m
                    );
            LISTBOX_AddString(hItem, words);
            }
            for(i=system.PVD_Number;i<8;i++)
            {
                LISTBOX_AddString(hItem, "None");
            }
        }

    	LISTBOX_SetSel(hItem,0);
    }
    else if (system.PVD_flag==1)
    {
        if(system.PVD_Number==0)
            Number=7;
        else
            Number=system.PVD_Number-1;
        for(i=Number;i>=0;i--)
    	{
	    	sprintf(words,"%d%02d%02d.%02d:%02d-%02d%02d.%02d:%02d"\
	    		,PVD_stack[i][0].Y,PVD_stack[i][0].M,PVD_stack[i][0].D,PVD_stack[i][0].h,PVD_stack[i][0].m\
	    		,PVD_stack[i][1].M,PVD_stack[i][1].D,PVD_stack[i][1].h,PVD_stack[i][1].m
	    		);
    	LISTBOX_AddString(hItem, words);
        }
    	for(i=7;i>system.PVD_Number;i--)
    	{
	    	sprintf(words,"%d%02d%02d.%02d:%02d-%02d%02d.%02d:%02d"\
	    		,PVD_stack[i][0].Y,PVD_stack[i][0].M,PVD_stack[i][0].D,PVD_stack[i][0].h,PVD_stack[i][0].m\
	    		,PVD_stack[i][1].M,PVD_stack[i][1].D,PVD_stack[i][1].h,PVD_stack[i][1].m
	    		);
    	LISTBOX_AddString(hItem, words);
    	}
        LISTBOX_SetSel(hItem,0);
    }

    LISTBOX_SetFont(hItem, GUI_FONT_8_ASCII);
    //LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	time[2]=(int)(system.PVD_Total_Time/1440);
	time[1]=(int)((system.PVD_Total_Time-time[2]*1440)/60);
	time[0]=system.PVD_Total_Time-time[2]*1440-time[1]*60;
    sprintf(words,"%d日%d时%d分",time[2],time[1],time[0]);
    TEXT_SetText(hItem, words);
    TEXT_SetFont(hItem, &GUI_FontST16);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
    case WM_KEY:
	    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
	    {
	    case GUI_KEY_UP:
	        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
	        {

	        }
	        WM_DefaultProc(pMsg);
	        break;
	    case GUI_KEY_DOWN:
	        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
	        {

	        }
	        break;
	    case GUI_KEY_LEFT:
	        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
	        {
	            WM_DeleteWindow(pMsg->hWin);
	            Xitong();
	        }
	        WM_DefaultProc(pMsg);
	        break;
	  	}
  	break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Xitong5(void);
WM_HWIN Xitong5(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
