/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_EDIT_0 (GUI_ID_USER + 0x02)
#define ID_EDIT_1 (GUI_ID_USER + 0x03)
#define ID_EDIT_2 (GUI_ID_USER + 0x04)
#define ID_EDIT_3 (GUI_ID_USER + 0x05)
#define ID_EDIT_4 (GUI_ID_USER + 0x06)
#define ID_EDIT_5 (GUI_ID_USER + 0x07)
#define ID_TEXT_1 (GUI_ID_USER + 0x08)
#define ID_TEXT_2 (GUI_ID_USER + 0x09)
#define ID_TEXT_3 (GUI_ID_USER + 0x0A)
#define ID_TEXT_4 (GUI_ID_USER + 0x0B)
#define ID_TEXT_5 (GUI_ID_USER + 0x0C)
#define ID_TEXT_6 (GUI_ID_USER + 0x0D)

// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 5, 16, 32, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 55, 16, 20, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 91, 16, 18, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 12, 40, 20, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 55, 40, 20, 16, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 91, 40, 18, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 38, 16, 16, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 75, 16, 16, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 36, 40, 16, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 75, 40, 16, 16, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 108, 16, 16, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 108, 40, 16, 16, 0, 0x0, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static WM_HWIN hWin_v[6];
  uint8_t i,ch[10];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"时间");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetDecMode(hItem,time.Y,2016,2100,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.Y+2000);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetDecMode(hItem,time.M,1,12,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.M);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetDecMode(hItem,time.D,1,31,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.D);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetDecMode(hItem,time.h,0,24,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.h);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetDecMode(hItem,time.m,0,59,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.m);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetDecMode(hItem,time.s,0,59,0,0);
    EDIT_EnableBlink(hItem,500,0);
    EDIT_SetValue(hItem,time.s);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem,"年");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem,"月");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);


    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem,"日");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem,"时");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem,"分");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem,"秒");
    TEXT_SetFont(hItem, &GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    for(i=0;i<6;i++)
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_EDIT_0+i);
    time.flags=1;
    WM_CreateTimer(pMsg->hWin,0x01,100,0);
    //WM_CreateTimer(pMsg->hWin,0x02,20,0);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by if(hItem=hWin_v[0])'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
    case WM_TIMER:
        switch(WM_GetTimerId(pMsg->Data.v))
        {
            case 1:
                for(i=0;i<6;i++)
                    WM_DisableWindow(hWin_v[i]);
                break;
            case 2:
                //WM_RestartTimer(pMsg->Data.v,20);
                //sprintf(ch,"%d",overtime);
                //TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0),ch);
                break;
        }
      break;
  case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
     case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(WM_IsEnabled(hItem))
            {

               WM_DisableWindow(hItem);
               EDIT_EnableBlink(hItem,500,0);
               if(hItem=hWin_v[0])
                    time.Y=EDIT_GetValue(hWin_v[0])-2000;
                if(hItem=hWin_v[1])
                    time.M=EDIT_GetValue(hWin_v[1]);
                if(hItem=hWin_v[2])
                    time.D=EDIT_GetValue(hWin_v[2]);
                if(hItem=hWin_v[3])
                    time.h=EDIT_GetValue(hWin_v[3]);
                if(hItem=hWin_v[4])
                    time.m=EDIT_GetValue(hWin_v[4]);
                if(hItem=hWin_v[5])
                    time.s=EDIT_GetValue(hWin_v[5]);
            }
            else
            {
                WM_EnableWindow(hItem);
                EDIT_EnableBlink(hItem,500,1);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_UP:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(!WM_IsEnabled(hItem))
            {
            if(hItem==hWin_v[0]);
            else if(hItem==hWin_v[1]);
            else if(hItem==hWin_v[2]);
            else if(hItem==hWin_v[3])
                WM_SetFocus(hWin_v[0]);
            else if(hItem==hWin_v[4])
                WM_SetFocus(hWin_v[1]);
            else if(hItem==hWin_v[5])
                WM_SetFocus(hWin_v[2]);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_DOWN:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(!WM_IsEnabled(hItem))
            {
            if(hItem==hWin_v[0])
                WM_SetFocus(hWin_v[3]);
            else if(hItem==hWin_v[1])
                WM_SetFocus(hWin_v[4]);
            else if(hItem==hWin_v[2])
                WM_SetFocus(hWin_v[5]);
            else if(hItem==hWin_v[3]);
            else if(hItem==hWin_v[4]);
            else if(hItem==hWin_v[5]);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(!WM_IsEnabled(hItem))
            {
            if(hItem==hWin_v[0])
            {
                measure.Setflag=1;system.PVD_Number=0;system.PVD_flag=0;system.PVD_Total_Time=0;
                WM_DeleteWindow(pMsg->hWin);
                Xitong();
            }
            else if(hItem==hWin_v[1])
            {
                WM_SetFocus(hWin_v[0]);
            }
            else if(hItem==hWin_v[2])
            {
                WM_SetFocus(hWin_v[1]);
            }
            else if(hItem==hWin_v[3])
            {
                WM_SetFocus(hWin_v[2]);
            }
            else if(hItem==hWin_v[4])
            {
                WM_SetFocus(hWin_v[3]);
            }
            else if(hItem==hWin_v[5])
            {
                WM_SetFocus(hWin_v[4]);
            }
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_RIGHT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(!WM_IsEnabled(hItem))
            {
            if(hItem==hWin_v[0])
                WM_SetFocus(hWin_v[1]);
            else if(hItem==hWin_v[1])
                WM_SetFocus(hWin_v[2]);
            else if(hItem==hWin_v[2])
                WM_SetFocus(hWin_v[3]);
            else if(hItem==hWin_v[3])
                WM_SetFocus(hWin_v[4]);
            else if(hItem==hWin_v[4])
                WM_SetFocus(hWin_v[5]);
            else if(hItem==hWin_v[5])
                {
                measure.Setflag=1;system.PVD_Number=0;system.PVD_flag=0;system.PVD_Total_Time=0;
                WM_DeleteWindow(pMsg->hWin);
                Xitong();
                }
            }
        }
        WM_DefaultProc(pMsg);
        break;
    }
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Xitong2(void);
WM_HWIN Xitong2(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
