/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
 #include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 19, 15, 90, 50, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static uint8_t listbox_offset=0;
  static uint8_t listbox_position=0;
  uint8_t ch[10];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem,"系统");
    TEXT_SetFont(hItem, &GUI_FontST16);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    //sprintf(ch,"输入类型%d",tongdao.Type);
    //LISTBOX_AddString(hItem, ch);
    LISTBOX_AddString(hItem, "密码");
    LISTBOX_AddString(hItem, "时间");
    LISTBOX_AddString(hItem, "通信");
    LISTBOX_AddString(hItem, "打印");
    LISTBOX_AddString(hItem, "掉电记录");
    LISTBOX_AddString(hItem, "清除缓存");
    LISTBOX_AddString(hItem, "恢复出厂");
    LISTBOX_SetFont(hItem, &GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    listbox_offset=0;
    listbox_position=0;
    time.flags=0;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
    case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            switch(listbox_position+listbox_offset)
            {
                case 0:WM_DeleteWindow(pMsg->hWin);Xitong1();break;
                case 1:WM_DeleteWindow(pMsg->hWin);Xitong2();break;
                case 2:WM_DeleteWindow(pMsg->hWin);Xitong3();break;
                case 3:WM_DeleteWindow(pMsg->hWin);Xitong4();break;
                case 4:WM_DeleteWindow(pMsg->hWin);Xitong5();break;
                case 5:WM_DeleteWindow(pMsg->hWin);Xitong6();break;
                case 6:WM_DeleteWindow(pMsg->hWin);Xitong7();break;
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_UP:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
                if(listbox_offset>0)
                    listbox_offset--;
                listbox_position=LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))-listbox_offset;
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_DOWN:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
                if(listbox_offset<3)
                    listbox_offset++;
                listbox_position=LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0))-listbox_offset;
        }
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            WM_DeleteWindow(pMsg->hWin);
            Menu_list();
        }
        WM_DefaultProc(pMsg);
        break;
  }
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Xitong(void);
WM_HWIN Xitong(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
