/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
 #include "Date.h"

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 16, 128, 18, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 16, 35, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 72, 35, 40, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
 extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static WM_HWIN hWin_v[2];
  uint8_t ch[10],i;
  static uint8_t focus=2;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem,"恢复出厂");
    TEXT_SetFont(hItem,&GUI_FontST16);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem,"确认重置？");
    TEXT_SetFont(hItem,&GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem,"确认");
    BUTTON_SetFont(hItem,&GUI_FontST16);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem,"取消");
    BUTTON_SetFont(hItem,&GUI_FontST16);


    WM_SetFocus(hItem);
    BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED,GUI_WHITE);
    BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    for(i=0;i<2;i++)
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0+i);
    // USER START (Optionally insert additional code for further widget initialization)
   // WM_CreateTimer(pMsg->hWin,0x01,30,0);

    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        system.Reset_All=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            WM_DeleteWindow(pMsg->hWin);
            Xitong();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
      WM_RestartTimer(pMsg->Data.v,50);

        sprintf(ch,"%d %d",hWin_v[0],WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,ch);
      break;
    case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_LEFT:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            if(focus==1)
            {
                focus=2;
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_WHITE);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_WHITE);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
            }
            else if(focus==2)
            {
                focus=1;
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_WHITE);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_WHITE);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_RIGHT:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            if(focus==1)
            {
                focus=2;
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_WHITE);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_WHITE);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
            }
            else if(focus==2)
            {
                focus=1;
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_WHITE);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_BLACK);
                BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_WHITE);
                WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
            }
        }
        WM_DefaultProc(pMsg);
        break;
    }
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Xitong7(void);
WM_HWIN Xitong7(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
