/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "Date.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x02)
#define ID_LISTBOX_1 (GUI_ID_USER + 0x03)
#define ID_EDIT_0 (GUI_ID_USER + 0x04)
#define ID_LISTBOX_2 (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_FontST16;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 128, 64, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 128, 16, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 0, 16, 64, 50, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_1, 64, 16, 50, 18, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 64, 32, 50, 16, 0, 0x64, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_2, 64, 47, 50, 17, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static WM_HWIN hWin_v[5];
  uint8_t i,ch[10];

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,"通信");
    TEXT_SetFont(hItem,&GUI_FontST16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "开关");
    LISTBOX_AddString(hItem, "地址");
    LISTBOX_AddString(hItem, "波特率");
    LISTBOX_SetFont(hItem,&GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1);
    LISTBOX_AddString(hItem, "关");
    LISTBOX_AddString(hItem, "开");
    LISTBOX_SetFont(hItem,&GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTBOX_SetSel(hItem,system.OnOff_485);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetDecMode(hItem,system.Addr_485,1,255,0,0);
    EDIT_SetValue(hItem,system.Addr_485);
    EDIT_SetCursorAtChar(hItem,2);
    EDIT_EnableBlink(hItem,500,1);
    EDIT_SetFont(hItem,GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_2);
    LISTBOX_AddString(hItem, "1200");
    LISTBOX_AddString(hItem, "2400");
    LISTBOX_AddString(hItem, "4800");
    LISTBOX_AddString(hItem, "9600");
    LISTBOX_AddString(hItem, "14400");
    LISTBOX_AddString(hItem, "19200");
    LISTBOX_AddString(hItem, "38400");
    LISTBOX_SetFont(hItem,&GUI_FontST16);
    LISTBOX_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    switch(system.Bps_485)
    {
        case 1200:    LISTBOX_SetSel(hItem,0);break;
        case 2400:    LISTBOX_SetSel(hItem,1);break;
        case 4800:    LISTBOX_SetSel(hItem,2);break;
        case 9600:    LISTBOX_SetSel(hItem,3);break;
        case 14400:    LISTBOX_SetSel(hItem,4);break;
        case 19200:    LISTBOX_SetSel(hItem,5);break;
        case 38400:    LISTBOX_SetSel(hItem,6);break;
    }
    // USER START (Optionally insert additional code for further widget initialization)
    for(i=0;i<4;i++)
        hWin_v[i]=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0+i);
       // WM_CreateTimer(pMsg->hWin,0x01,30,0);
    // USER END
    break;
    // USER START (Optionally insert additional code for further Ids)
case WM_TIMER:
      WM_RestartTimer(pMsg->Data.v,50);
        sprintf(ch,"%d %d",hWin_v[0],WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem,ch);
      break;
    // USER END
  // USER START (Optionally insert additional message handling)
  case WM_KEY:
    switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
    {
    case GUI_KEY_ENTER:
        if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
                i=LISTBOX_GetSel(hWin_v[0]);
                hItem=WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_1+i);
                WM_SetFocus(hItem);
            }
            else if(hItem==hWin_v[1])
            {
                if(LISTBOX_GetSel(hWin_v[1])==0)
                    system.OnOff_485=1200;
                if(LISTBOX_GetSel(hWin_v[1])==1)
                    system.OnOff_485=2400;
                if(LISTBOX_GetSel(hWin_v[1])==2)
                    system.OnOff_485=4800;
                if(LISTBOX_GetSel(hWin_v[1])==3)
                    system.OnOff_485=9600;
                if(LISTBOX_GetSel(hWin_v[1])==4)
                    system.OnOff_485=14400;
                if(LISTBOX_GetSel(hWin_v[1])==0)
                    system.OnOff_485=19200;
                if(LISTBOX_GetSel(hWin_v[1])==0)
                    system.OnOff_485=38400;
                WM_SetFocus(hWin_v[0]);
            }
            else if(hItem==hWin_v[2])
            {
                system.Addr_485=EDIT_GetValue(hWin_v[2]);
                WM_SetFocus(hWin_v[0]);
            }
            else if(hItem==hWin_v[3])
            {
                system.Bps_485=LISTBOX_GetSel(hWin_v[3]);
                WM_SetFocus(hWin_v[0]);
            }
        }
        WM_DefaultProc(pMsg);
        break;
    case GUI_KEY_LEFT:
        if(!(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt))
        {
            hItem=WM_GetFocussedWindow();
            if(hItem==hWin_v[0])
            {
            WM_DeleteWindow(pMsg->hWin);
            Xitong();
            system.SChange_485=1;
            }
        }
        WM_DefaultProc(pMsg);
        break;
  }
  break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Xitong3(void);
WM_HWIN Xitong3(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
